### ISSUE TITLE
Worker emulator didn't work on Android 8.1

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/js-dos.com#116]
```
emulators-ui.js:1 DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
    at s.value (http://localhost/emulators/emulators.js:1:98280)
    at new s (http://localhost/emulators/emulators.js:1:98156)
    at new i (http://localhost/emulators/emulators.js:1:101945)
    at http://localhost/emulators/emulators.js:1:101398
    at new Promise (<anonymous>)
    at Object.r.default (http://localhost/emulators/emulators.js:1:101368)
    at e.<anonymous> (http://localhost/emulators/emulators.js:1:115819)
    at l (http://localhost/static/js/2.ca1c79bb.chunk.js:2:982200)
    at Generator._invoke (http://localhost/static/js/2.ca1c79bb.chunk.js:2:981988)
    at Generator.forEach.e.(anonymous function) [as next] (http://localhost/static/js/2.ca1c79bb.chunk.js:2:982623)
(anonymous) @ emulators-ui.js:1
emulators.js:1 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': #<Module> could not be cloned.
    at s.value (http://localhost/emulators/emulators.js:1:98280)
    at new s (http://localhost/emulators/emulators.js:1:98156)
    at new i (http://localhost/emulators/emulators.js:1:101945)
    at http://localhost/emulators/emulators.js:1:101398
    at new Promise (<anonymous>)
    at Object.r.default (http://localhost/emulators/emulators.js:1:101368)
    at e.<anonymous> (http://localhost/emulators/emulators.js:1:115819)
    at l (http://localhost/static/js/2.ca1c79bb.chunk.js:2:982200)
    at Generator._invoke (http://localhost/static/js/2.ca1c79bb.chunk.js:2:981988)
    at Generator.forEach.e.(anonymous function) [as next] (http://localhost/static/js/2.ca1c79bb.chunk.js:2:982623)
```

**Comment by caiiiycuk** [comment]
Fixed
