### ISSUE TITLE
GTA didn't start

### ISSUE THREAD

**Issue by caiiiycuk** [caiiiycuk/js-dos.com#122]
```006f5e46:0x2222e Uncaught RuntimeError: unreachable
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x2222e)
    at InitPageHandler::writeb(unsigned int, unsigned int) (<anonymous>:wasm-function[422]:0x223a0)
    at mem_writeb(unsigned int, unsigned char) (<anonymous>:wasm-function[2428]:0xf929e)
    at InitPageHandler::writeb(unsigned int, unsigned int) (<anonymous>:wasm-function[422]:0x223ad)
    at DoString(STRING_OP).2 (<anonymous>:wasm-function[499]:0x841fd)
    at CPU_Core_Normal_Run() (<anonymous>:wasm-function[498]:0x59319)
    at Normal_Loop() (<anonymous>:wasm-function[65]:0x2ea8)
    at DOSBOX_RunMachine() (<anonymous>:wasm-function[66]:0x300b)
    at CALLBACK_RunRealInt(unsigned char) (<anonymous>:wasm-function[626]:0x8b037)
    at DOS_Shell::Execute(char*, char*) (<anonymous>:wasm-function[1623]:0xc7c50)
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x2222e
InitPageHandler::writeb(unsigned int, unsigned int) @ 006f5e46:0x223a0
mem_writeb(unsigned int, unsigned char) @ 006f5e46:0xf929e
InitPageHandler::writeb(unsigned int, unsigned int) @ 006f5e46:0x223ad
DoString(STRING_OP).2 @ 006f5e46:0x841fd
CPU_Core_Normal_Run() @ 006f5e46:0x59319
Normal_Loop() @ 006f5e46:0x2ea8
DOSBOX_RunMachine() @ 006f5e46:0x300b
CALLBACK_RunRealInt(unsigned char) @ 006f5e46:0x8b037
DOS_Shell::Execute(char*, char*) @ 006f5e46:0xc7c50
DOS_Shell::DoCommand(char*) @ 006f5e46:0xc1279
DOS_Shell::ParseLine(char*) @ 006f5e46:0xbfa09
DOS_Shell::Run() @ 006f5e46:0xbfe40
SHELL_Init() @ 006f5e46:0xc0c52
jsdos_main(Config*) @ 006f5e46:0x1073d3
server_run() @ 006f5e46:0x1077ee
runRuntime @ 006f5e46:0x114eae
ret.<computed> @ wworker.js:5770
(anonymous) @ wworker.js:5848
Module.receive @ wworker.js:1489
006f5e46:0x2222e Uncaught RuntimeError: unreachable
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x2222e)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at ret.<computed> (https://dos.zone/emulators/wworker.js:5770:35)
    at Object.Module._mouseMove (https://dos.zone/emulators/wworker.js:6104:75)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x2222e
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
Module._mouseMove @ wworker.js:6104
onmessage @ wworker.js:1498
2006f5e46:0x300b Uncaught RuntimeError: function signature mismatch
    at DOSBOX_RunMachine() (<anonymous>:wasm-function[66]:0x300b)
    at PAGING_PageFault(unsigned int, unsigned int, unsigned int) (<anonymous>:wasm-function[403]:0x21540)
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x21d99)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at Object.ret.<computed> [as _mouseMove] (https://dos.zone/emulators/wworker.js:5770:35)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
DOSBOX_RunMachine() @ 006f5e46:0x300b
PAGING_PageFault(unsigned int, unsigned int, unsigned int) @ 006f5e46:0x21540
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x21d99
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
onmessage @ wworker.js:1498
8006f5e46:0x2222e Uncaught RuntimeError: unreachable
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x2222e)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at Object.ret.<computed> [as _mouseMove] (https://dos.zone/emulators/wworker.js:5770:35)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x2222e
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
onmessage @ wworker.js:1498
5006f5e46:0x300b Uncaught RuntimeError: function signature mismatch
    at DOSBOX_RunMachine() (<anonymous>:wasm-function[66]:0x300b)
    at PAGING_PageFault(unsigned int, unsigned int, unsigned int) (<anonymous>:wasm-function[403]:0x21540)
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x21d99)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at Object.ret.<computed> [as _mouseMove] (https://dos.zone/emulators/wworker.js:5770:35)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
DOSBOX_RunMachine() @ 006f5e46:0x300b
PAGING_PageFault(unsigned int, unsigned int, unsigned int) @ 006f5e46:0x21540
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x21d99
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
onmessage @ wworker.js:1498
2006f5e46:0x2222e Uncaught RuntimeError: unreachable
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x2222e)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at Object.ret.<computed> [as _mouseMove] (https://dos.zone/emulators/wworker.js:5770:35)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x2222e
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
onmessage @ wworker.js:1498
2006f5e46:0x300b Uncaught RuntimeError: function signature mismatch
    at DOSBOX_RunMachine() (<anonymous>:wasm-function[66]:0x300b)
    at PAGING_PageFault(unsigned int, unsigned int, unsigned int) (<anonymous>:wasm-function[403]:0x21540)
    at InitPageHandler::InitPage(unsigned int, bool) (<anonymous>:wasm-function[419]:0x21d99)
    at InitPageHandler::readw(unsigned int) (<anonymous>:wasm-function[420]:0x222c8)
    at mem_readw(unsigned int) (<anonymous>:wasm-function[2426]:0xf91ed)
    at Mouse_CursorMoved(float, float, float, float, bool) (<anonymous>:wasm-function[2866]:0x10a4ff)
    at server_mouse_moved(float, float, unsigned long long) (<anonymous>:wasm-function[2806]:0x107753)
    at legalstub$mouseMove (<anonymous>:wasm-function[3901]:0x13bb7a)
    at Object.ret.<computed> [as _mouseMove] (https://dos.zone/emulators/wworker.js:5770:35)
    at onmessage (https://dos.zone/emulators/wworker.js:1498:1259)
DOSBOX_RunMachine() @ 006f5e46:0x300b
PAGING_PageFault(unsigned int, unsigned int, unsigned int) @ 006f5e46:0x21540
InitPageHandler::InitPage(unsigned int, bool) @ 006f5e46:0x21d99
InitPageHandler::readw(unsigned int) @ 006f5e46:0x222c8
mem_readw(unsigned int) @ 006f5e46:0xf91ed
Mouse_CursorMoved(float, float, float, float, bool) @ 006f5e46:0x10a4ff
server_mouse_moved(float, float, unsigned long long) @ 006f5e46:0x107753
legalstub$mouseMove @ 006f5e46:0x13bb7a
ret.<computed> @ wworker.js:5770
onmessage @ wworker.js:1498
```

**Comment by caiiiycuk** [comment]
FIxed
