### ISSUE TITLE
this.breakLines(...).flat is not a function error. Please help. Error after calling npx create-dosbox my-app

### ISSUE THREAD

**Issue by sluke817** [caiiiycuk/js-dos.com#214]
at ScreenManager.forceLineReturn (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/utils/screen-manager.js:172:56)
    at ScreenManager.render (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/utils/screen-manager.js:81:20)
    at InputPrompt.render (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/prompts/input.js:67:17)
    at InputPrompt._run (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/prompts/input.js:34:10)
    at Promise (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/prompts/base.js:61:12)
    at new Promise (<anonymous>)
    at InputPrompt.run (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/prompts/base.js:60:12)
    at defer (/usr/local/lib/node_modules/create-dosbox/node_modules/inquirer/lib/ui/prompt.js:105:30)
    at Observable._subscribe (/usr/local/lib/node_modules/create-dosbox/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/usr/local/lib/node_modules/create-dosbox/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)

**Comment by caiiiycuk** [comment]
I guess you using incompatible node version. Which version do you use?

**Comment by sluke817** [comment]
Hello,
I believe I am using the most up to date node version. What do you think?


Luke Schaefer
University of Missouri - Columbia (18186970)
College of Engineering - BS Computer Science
***@***.***
________________________________

**Comment by caiiiycuk** [comment]
Can you try if error exists on node v14?

**Comment by sluke817** [comment]
How/where can I install that?

Luke Schaefer
University of Missouri - Columbia (18186970)
College of Engineering - BS Computer Science
***@***.***
________________________________

**Comment by caiiiycuk** [comment]
https://nodejs.org/download/release/v14.19.1/
